language: rust
rust:
  - 1.35.0
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy --tests -- -D warnings
  - cargo test
